// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     nginx-lint:plugin@4.0.0

package nginx_lint_plugin_config_api

import (
	"github.com/walf443/nginx-lint/plugins/go/nginx-lint-plugin/bindings/nginx_lint_plugin_data_types"
	"github.com/walf443/nginx-lint/plugins/go/nginx-lint-plugin/bindings/nginx_lint_plugin_parser_types"
	"github.com/walf443/nginx-lint/plugins/go/nginx-lint-plugin/bindings/nginx_lint_plugin_types"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type Fix = nginx_lint_plugin_types.Fix
type ArgumentType = nginx_lint_plugin_data_types.ArgumentType
type ArgumentInfo = nginx_lint_plugin_data_types.ArgumentInfo
type CommentInfo = nginx_lint_plugin_data_types.CommentInfo
type BlankLineInfo = nginx_lint_plugin_data_types.BlankLineInfo
type DirectiveData = nginx_lint_plugin_data_types.DirectiveData
type FlatItem = nginx_lint_plugin_parser_types.ConfigItem

// The entire config as one flat value (see the `snapshot` function)
type ConfigSnapshot struct {
	// Flat array of all config items (DFS order); directive items
	// reference their block children via child-indices
	AllItems []nginx_lint_plugin_parser_types.ConfigItem
	// Indices of top-level items in all-items
	TopLevelIndices []uint32
	// Include context (parent block names from the include directive)
	IncludeContext []string
}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [resource-drop]directive
func resourceDropDirective(handle int32)

// An nginx directive (resource backed by host data)
type Directive struct {
	handle *witRuntime.Handle
}

func (self *Directive) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Directive) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Directive) Handle() int32 {
	return self.handle.Use()
}

func (self *Directive) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropDirective(handle)
	}
}

func DirectiveFromOwnHandle(handleValue int32) *Directive {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Directive{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropDirective(handleValue)
		}
	}, 0)
	return value
}

func DirectiveFromBorrowHandle(handleValue int32) *Directive {
	handle := witRuntime.MakeHandle(handleValue)
	return &Directive{handle}
}

const (
	ConfigItemDirectiveItem uint8 = 0
	ConfigItemCommentItem   uint8 = 1
	ConfigItemBlankLineItem uint8 = 2
)

// A config item (directive, comment, or blank line)
type ConfigItem struct {
	tag   uint8
	value any
}

func (self ConfigItem) Tag() uint8 {
	return self.tag
}

func (self ConfigItem) DirectiveItem() *Directive {
	if self.tag != ConfigItemDirectiveItem {
		panic("tag mismatch")
	}
	return self.value.(*Directive)
}
func (self ConfigItem) CommentItem() nginx_lint_plugin_data_types.CommentInfo {
	if self.tag != ConfigItemCommentItem {
		panic("tag mismatch")
	}
	return self.value.(nginx_lint_plugin_data_types.CommentInfo)
}
func (self ConfigItem) BlankLineItem() nginx_lint_plugin_data_types.BlankLineInfo {
	if self.tag != ConfigItemBlankLineItem {
		panic("tag mismatch")
	}
	return self.value.(nginx_lint_plugin_data_types.BlankLineInfo)
}

func MakeConfigItemDirectiveItem(value *Directive) ConfigItem {
	return ConfigItem{ConfigItemDirectiveItem, value}
}
func MakeConfigItemCommentItem(value nginx_lint_plugin_data_types.CommentInfo) ConfigItem {
	return ConfigItem{ConfigItemCommentItem, value}
}
func MakeConfigItemBlankLineItem(value nginx_lint_plugin_data_types.BlankLineInfo) ConfigItem {
	return ConfigItem{ConfigItemBlankLineItem, value}
}

// A directive paired with its parent block context
type DirectiveContext struct {
	Directive   *Directive
	ParentStack []string
	Depth       uint32
}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [resource-drop]config
func resourceDropConfig(handle int32)

// The parsed nginx configuration (resource backed by host data)
type Config struct {
	handle *witRuntime.Handle
}

func (self *Config) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Config) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Config) Handle() int32 {
	return self.handle.Use()
}

func (self *Config) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropConfig(handle)
	}
}

func ConfigFromOwnHandle(handleValue int32) *Config {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Config{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropConfig(handleValue)
		}
	}, 0)
	return value
}

func ConfigFromBorrowHandle(handleValue int32) *Config {
	handle := witRuntime.MakeHandle(handleValue)
	return &Config{handle}
}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.data
func wasm_import_method_directive_data(arg0 int32, arg1 uintptr)

func (self *Directive) Data() nginx_lint_plugin_data_types.DirectiveData {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (56 + 23*4), 4))
	wasm_import_method_directive_data((self).Handle(), returnArea)
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := make([]nginx_lint_plugin_data_types.ArgumentInfo, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))), index*(16+5*4))
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
		value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

		result = append(result, nginx_lint_plugin_data_types.ArgumentInfo{value0, value1, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (16 + 4*4))))})
	}

	value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 4*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 5*4))))
	value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 6*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 7*4))))
	value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 8*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 9*4))))
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 11*4)))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 12*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 13*4))))

		option = witTypes.Some[string](value5)
	default:
		panic("unreachable")
	}
	var option7 witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 14*4)))) {
	case 0:

		option7 = witTypes.None[string]()
	case 1:
		value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 15*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 16*4))))

		option7 = witTypes.Some[string](value6)
	default:
		panic("unreachable")
	}
	var option9 witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 17*4)))) {
	case 0:

		option9 = witTypes.None[string]()
	case 1:
		value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 18*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 19*4))))

		option9 = witTypes.Some[string](value8)
	default:
		panic("unreachable")
	}
	var option11 witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 20*4)))) {
	case 0:

		option11 = witTypes.None[string]()
	case 1:
		value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 21*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 22*4))))

		option11 = witTypes.Some[string](value10)
	default:
		panic("unreachable")
	}
	var option12 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (32 + 23*4)))) {
	case 0:

		option12 = witTypes.None[uint32]()
	case 1:

		option12 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (36 + 23*4)))))
	default:
		panic("unreachable")
	}
	var option13 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 23*4)))) {
	case 0:

		option13 = witTypes.None[uint32]()
	case 1:

		option13 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (44 + 23*4)))))
	default:
		panic("unreachable")
	}
	var option14 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (48 + 23*4)))) {
	case 0:

		option14 = witTypes.None[uint32]()
	case 1:

		option14 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (52 + 23*4)))))
	default:
		panic("unreachable")
	}
	result15 := nginx_lint_plugin_data_types.DirectiveData{value, result, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (12 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (20 + 4*4)))), value2, value3, value4, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 10*4)))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (25 + 10*4)))) != 0), option, option7, option9, option11, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 23*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (28 + 23*4)))), option12, option13, option14}
	return result15

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.name
func wasm_import_method_directive_name(arg0 int32, arg1 uintptr)

func (self *Directive) Name() string {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_directive_name((self).Handle(), returnArea)
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.is
func wasm_import_method_directive_is(arg0 int32, arg1 uintptr, arg2 uint32) int32

func (self *Directive) Is(name string) bool {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)
	result := wasm_import_method_directive_is((self).Handle(), uintptr(utf8), uint32(len(name)))
	return (result != 0)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.first-arg
func wasm_import_method_directive_first_arg(arg0 int32, arg1 uintptr)

func (self *Directive) FirstArg() witTypes.Option[string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_directive_first_arg((self).Handle(), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.first-arg-is
func wasm_import_method_directive_first_arg_is(arg0 int32, arg1 uintptr, arg2 uint32) int32

func (self *Directive) FirstArgIs(value string) bool {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	utf8 := unsafe.Pointer(unsafe.StringData(value))
	pinner.Pin(utf8)
	result := wasm_import_method_directive_first_arg_is((self).Handle(), uintptr(utf8), uint32(len(value)))
	return (result != 0)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.arg-at
func wasm_import_method_directive_arg_at(arg0 int32, arg1 int32, arg2 uintptr)

func (self *Directive) ArgAt(index uint32) witTypes.Option[string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_directive_arg_at((self).Handle(), int32(index), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.last-arg
func wasm_import_method_directive_last_arg(arg0 int32, arg1 uintptr)

func (self *Directive) LastArg() witTypes.Option[string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_directive_last_arg((self).Handle(), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.has-arg
func wasm_import_method_directive_has_arg(arg0 int32, arg1 uintptr, arg2 uint32) int32

func (self *Directive) HasArg(value string) bool {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	utf8 := unsafe.Pointer(unsafe.StringData(value))
	pinner.Pin(utf8)
	result := wasm_import_method_directive_has_arg((self).Handle(), uintptr(utf8), uint32(len(value)))
	return (result != 0)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.arg-count
func wasm_import_method_directive_arg_count(arg0 int32) int32

func (self *Directive) ArgCount() uint32 {

	result := wasm_import_method_directive_arg_count((self).Handle())
	return uint32(result)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.args
func wasm_import_method_directive_args(arg0 int32, arg1 uintptr)

func (self *Directive) Args() []nginx_lint_plugin_data_types.ArgumentInfo {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_directive_args((self).Handle(), returnArea)
	result := make([]nginx_lint_plugin_data_types.ArgumentInfo, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(16+5*4))
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

		result = append(result, nginx_lint_plugin_data_types.ArgumentInfo{value, value0, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (16 + 4*4))))})
	}

	result1 := result
	return result1

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.line
func wasm_import_method_directive_line(arg0 int32) int32

func (self *Directive) Line() uint32 {

	result := wasm_import_method_directive_line((self).Handle())
	return uint32(result)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.column
func wasm_import_method_directive_column(arg0 int32) int32

func (self *Directive) Column() uint32 {

	result := wasm_import_method_directive_column((self).Handle())
	return uint32(result)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.start-offset
func wasm_import_method_directive_start_offset(arg0 int32) int32

func (self *Directive) StartOffset() uint32 {

	result := wasm_import_method_directive_start_offset((self).Handle())
	return uint32(result)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.end-offset
func wasm_import_method_directive_end_offset(arg0 int32) int32

func (self *Directive) EndOffset() uint32 {

	result := wasm_import_method_directive_end_offset((self).Handle())
	return uint32(result)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.leading-whitespace
func wasm_import_method_directive_leading_whitespace(arg0 int32, arg1 uintptr)

func (self *Directive) LeadingWhitespace() string {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_directive_leading_whitespace((self).Handle(), returnArea)
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.trailing-whitespace
func wasm_import_method_directive_trailing_whitespace(arg0 int32, arg1 uintptr)

func (self *Directive) TrailingWhitespace() string {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_directive_trailing_whitespace((self).Handle(), returnArea)
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.space-before-terminator
func wasm_import_method_directive_space_before_terminator(arg0 int32, arg1 uintptr)

func (self *Directive) SpaceBeforeTerminator() string {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_directive_space_before_terminator((self).Handle(), returnArea)
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.has-block
func wasm_import_method_directive_has_block(arg0 int32) int32

func (self *Directive) HasBlock() bool {

	result := wasm_import_method_directive_has_block((self).Handle())
	return (result != 0)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.block-items
func wasm_import_method_directive_block_items(arg0 int32, arg1 uintptr)

func (self *Directive) BlockItems() []ConfigItem {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_directive_block_items((self).Handle(), returnArea)
	result := make([]ConfigItem, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(16+7*4))
		var variant ConfigItem
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
		case 0:

			variant = MakeConfigItemDirectiveItem(DirectiveFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(base), 4))))))

		case 1:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))))
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))))
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 6*4))))

			variant = MakeConfigItemCommentItem(nginx_lint_plugin_data_types.CommentInfo{value, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (3 * 4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 3*4)))), value0, value1, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 7*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 7*4))))})

		case 2:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

			variant = MakeConfigItemBlankLineItem(nginx_lint_plugin_data_types.BlankLineInfo{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 4))), value2, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))))})

		default:
			panic("unreachable")
		}

		result = append(result, variant)
	}

	result3 := result
	return result3

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.block-is-raw
func wasm_import_method_directive_block_is_raw(arg0 int32) int32

func (self *Directive) BlockIsRaw() bool {

	result := wasm_import_method_directive_block_is_raw((self).Handle())
	return (result != 0)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.replace-with
func wasm_import_method_directive_replace_with(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Directive) ReplaceWith(newText string) nginx_lint_plugin_types.Fix {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 7*4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(newText))
	pinner.Pin(utf8)
	wasm_import_method_directive_replace_with((self).Handle(), uintptr(utf8), uint32(len(newText)), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
	var option1 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 6*4)))) {
	case 0:

		option1 = witTypes.None[uint32]()
	case 1:

		option1 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 6*4)))))
	default:
		panic("unreachable")
	}
	var option2 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (12 + 6*4)))) {
	case 0:

		option2 = witTypes.None[uint32]()
	case 1:

		option2 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 6*4)))))
	default:
		panic("unreachable")
	}
	result := nginx_lint_plugin_types.Fix{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0))), option, value0, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (1 + 6*4)))) != 0), option1, option2}
	return result

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.delete-line-fix
func wasm_import_method_directive_delete_line_fix(arg0 int32, arg1 uintptr)

func (self *Directive) DeleteLineFix() nginx_lint_plugin_types.Fix {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 7*4), 4))
	wasm_import_method_directive_delete_line_fix((self).Handle(), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
	var option1 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 6*4)))) {
	case 0:

		option1 = witTypes.None[uint32]()
	case 1:

		option1 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 6*4)))))
	default:
		panic("unreachable")
	}
	var option2 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (12 + 6*4)))) {
	case 0:

		option2 = witTypes.None[uint32]()
	case 1:

		option2 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 6*4)))))
	default:
		panic("unreachable")
	}
	result := nginx_lint_plugin_types.Fix{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0))), option, value0, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (1 + 6*4)))) != 0), option1, option2}
	return result

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.insert-after
func wasm_import_method_directive_insert_after(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Directive) InsertAfter(newText string) nginx_lint_plugin_types.Fix {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 7*4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(newText))
	pinner.Pin(utf8)
	wasm_import_method_directive_insert_after((self).Handle(), uintptr(utf8), uint32(len(newText)), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
	var option1 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 6*4)))) {
	case 0:

		option1 = witTypes.None[uint32]()
	case 1:

		option1 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 6*4)))))
	default:
		panic("unreachable")
	}
	var option2 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (12 + 6*4)))) {
	case 0:

		option2 = witTypes.None[uint32]()
	case 1:

		option2 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 6*4)))))
	default:
		panic("unreachable")
	}
	result := nginx_lint_plugin_types.Fix{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0))), option, value0, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (1 + 6*4)))) != 0), option1, option2}
	return result

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.insert-before
func wasm_import_method_directive_insert_before(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Directive) InsertBefore(newText string) nginx_lint_plugin_types.Fix {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 7*4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(newText))
	pinner.Pin(utf8)
	wasm_import_method_directive_insert_before((self).Handle(), uintptr(utf8), uint32(len(newText)), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
	var option1 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 6*4)))) {
	case 0:

		option1 = witTypes.None[uint32]()
	case 1:

		option1 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 6*4)))))
	default:
		panic("unreachable")
	}
	var option2 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (12 + 6*4)))) {
	case 0:

		option2 = witTypes.None[uint32]()
	case 1:

		option2 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 6*4)))))
	default:
		panic("unreachable")
	}
	result := nginx_lint_plugin_types.Fix{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0))), option, value0, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (1 + 6*4)))) != 0), option1, option2}
	return result

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.insert-after-many
func wasm_import_method_directive_insert_after_many(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Directive) InsertAfterMany(lines []string) nginx_lint_plugin_types.Fix {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 7*4), 4))
	slice := lines
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf8 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

	}

	wasm_import_method_directive_insert_after_many((self).Handle(), uintptr(result), length, returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
	var option1 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 6*4)))) {
	case 0:

		option1 = witTypes.None[uint32]()
	case 1:

		option1 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 6*4)))))
	default:
		panic("unreachable")
	}
	var option2 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (12 + 6*4)))) {
	case 0:

		option2 = witTypes.None[uint32]()
	case 1:

		option2 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 6*4)))))
	default:
		panic("unreachable")
	}
	result3 := nginx_lint_plugin_types.Fix{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0))), option, value0, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (1 + 6*4)))) != 0), option1, option2}
	return result3

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]directive.insert-before-many
func wasm_import_method_directive_insert_before_many(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Directive) InsertBeforeMany(lines []string) nginx_lint_plugin_types.Fix {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 7*4), 4))
	slice := lines
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf8 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

	}

	wasm_import_method_directive_insert_before_many((self).Handle(), uintptr(result), length, returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
	var option1 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 6*4)))) {
	case 0:

		option1 = witTypes.None[uint32]()
	case 1:

		option1 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 6*4)))))
	default:
		panic("unreachable")
	}
	var option2 witTypes.Option[uint32]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (12 + 6*4)))) {
	case 0:

		option2 = witTypes.None[uint32]()
	case 1:

		option2 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 6*4)))))
	default:
		panic("unreachable")
	}
	result3 := nginx_lint_plugin_types.Fix{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0))), option, value0, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (1 + 6*4)))) != 0), option1, option2}
	return result3

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]config.snapshot
func wasm_import_method_config_snapshot(arg0 int32, arg1 uintptr)

func (self *Config) Snapshot() ConfigSnapshot {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (6 * 4), 4))
	wasm_import_method_config_snapshot((self).Handle(), returnArea)
	result20 := make([]nginx_lint_plugin_parser_types.ConfigItem, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(56+26*4))
		var variant nginx_lint_plugin_parser_types.ConfigItemValue
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))))
			result := make([]nginx_lint_plugin_data_types.ArgumentInfo, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4)))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))), index*(16+5*4))
				value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
				value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

				result = append(result, nginx_lint_plugin_data_types.ArgumentInfo{value0, value1, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (16 + 4*4))))})
			}

			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 6*4))))
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 7*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 8*4))))
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 9*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 10*4))))
			var option witTypes.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 12*4)))) {
			case 0:

				option = witTypes.None[string]()
			case 1:
				value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 13*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 14*4))))

				option = witTypes.Some[string](value5)
			default:
				panic("unreachable")
			}
			var option7 witTypes.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 15*4)))) {
			case 0:

				option7 = witTypes.None[string]()
			case 1:
				value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 16*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 17*4))))

				option7 = witTypes.Some[string](value6)
			default:
				panic("unreachable")
			}
			var option9 witTypes.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 18*4)))) {
			case 0:

				option9 = witTypes.None[string]()
			case 1:
				value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 19*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 20*4))))

				option9 = witTypes.Some[string](value8)
			default:
				panic("unreachable")
			}
			var option11 witTypes.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 21*4)))) {
			case 0:

				option11 = witTypes.None[string]()
			case 1:
				value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 22*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 23*4))))

				option11 = witTypes.Some[string](value10)
			default:
				panic("unreachable")
			}
			var option12 witTypes.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (32 + 24*4)))) {
			case 0:

				option12 = witTypes.None[uint32]()
			case 1:

				option12 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (36 + 24*4)))))
			default:
				panic("unreachable")
			}
			var option13 witTypes.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 24*4)))) {
			case 0:

				option13 = witTypes.None[uint32]()
			case 1:

				option13 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (44 + 24*4)))))
			default:
				panic("unreachable")
			}
			var option14 witTypes.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 24*4)))) {
			case 0:

				option14 = witTypes.None[uint32]()
			case 1:

				option14 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (52 + 24*4)))))
			default:
				panic("unreachable")
			}

			variant = nginx_lint_plugin_parser_types.MakeConfigItemValueDirectiveItem(nginx_lint_plugin_data_types.DirectiveData{value, result, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (5 * 4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 5*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 5*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (16 + 5*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (20 + 5*4)))), value2, value3, value4, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 11*4)))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (25 + 11*4)))) != 0), option, option7, option9, option11, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (24 + 24*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (28 + 24*4)))), option12, option13, option14})

		case 1:
			value15 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))))
			value16 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))))
			value17 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 6*4))))

			variant = nginx_lint_plugin_parser_types.MakeConfigItemValueCommentItem(nginx_lint_plugin_data_types.CommentInfo{value15, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (3 * 4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 3*4)))), value16, value17, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 7*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 7*4))))})

		case 2:
			value18 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

			variant = nginx_lint_plugin_parser_types.MakeConfigItemValueBlankLineItem(nginx_lint_plugin_data_types.BlankLineInfo{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 4))), value18, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))))})

		default:
			panic("unreachable")
		}
		value19 := unsafe.Slice((*uint32)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 24*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 25*4))))

		result20 = append(result20, nginx_lint_plugin_parser_types.ConfigItem{variant, value19})
	}

	value21 := unsafe.Slice((*uint32)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
	result23 := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4)))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))), index*(2*4))
		value22 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

		result23 = append(result23, value22)
	}

	result24 := ConfigSnapshot{result20, value21, result23}
	return result24

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]config.snapshot-filtered
func wasm_import_method_config_snapshot_filtered(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Config) SnapshotFiltered(names []string) ConfigSnapshot {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (6 * 4), 4))
	slice := names
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf8 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

	}

	wasm_import_method_config_snapshot_filtered((self).Handle(), uintptr(result), length, returnArea)
	result21 := make([]nginx_lint_plugin_parser_types.ConfigItem, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(56+26*4))
		var variant nginx_lint_plugin_parser_types.ConfigItemValue
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))))
			result2 := make([]nginx_lint_plugin_data_types.ArgumentInfo, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4)))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))), index*(16+5*4))
				value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
				value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

				result2 = append(result2, nginx_lint_plugin_data_types.ArgumentInfo{value0, value1, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 4*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (16 + 4*4))))})
			}

			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 6*4))))
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 7*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 8*4))))
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 9*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 10*4))))
			var option witTypes.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 12*4)))) {
			case 0:

				option = witTypes.None[string]()
			case 1:
				value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 13*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 14*4))))

				option = witTypes.Some[string](value6)
			default:
				panic("unreachable")
			}
			var option8 witTypes.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 15*4)))) {
			case 0:

				option8 = witTypes.None[string]()
			case 1:
				value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 16*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 17*4))))

				option8 = witTypes.Some[string](value7)
			default:
				panic("unreachable")
			}
			var option10 witTypes.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 18*4)))) {
			case 0:

				option10 = witTypes.None[string]()
			case 1:
				value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 19*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 20*4))))

				option10 = witTypes.Some[string](value9)
			default:
				panic("unreachable")
			}
			var option12 witTypes.Option[string]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 21*4)))) {
			case 0:

				option12 = witTypes.None[string]()
			case 1:
				value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 22*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 23*4))))

				option12 = witTypes.Some[string](value11)
			default:
				panic("unreachable")
			}
			var option13 witTypes.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (32 + 24*4)))) {
			case 0:

				option13 = witTypes.None[uint32]()
			case 1:

				option13 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (36 + 24*4)))))
			default:
				panic("unreachable")
			}
			var option14 witTypes.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 24*4)))) {
			case 0:

				option14 = witTypes.None[uint32]()
			case 1:

				option14 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (44 + 24*4)))))
			default:
				panic("unreachable")
			}
			var option15 witTypes.Option[uint32]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 24*4)))) {
			case 0:

				option15 = witTypes.None[uint32]()
			case 1:

				option15 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (52 + 24*4)))))
			default:
				panic("unreachable")
			}

			variant = nginx_lint_plugin_parser_types.MakeConfigItemValueDirectiveItem(nginx_lint_plugin_data_types.DirectiveData{value, result2, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (5 * 4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 5*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 5*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (16 + 5*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (20 + 5*4)))), value3, value4, value5, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 11*4)))) != 0), (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (25 + 11*4)))) != 0), option, option8, option10, option12, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (24 + 24*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (28 + 24*4)))), option13, option14, option15})

		case 1:
			value16 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))))
			value17 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))))
			value18 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 6*4))))

			variant = nginx_lint_plugin_parser_types.MakeConfigItemValueCommentItem(nginx_lint_plugin_data_types.CommentInfo{value16, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (3 * 4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 3*4)))), value17, value18, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 7*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 7*4))))})

		case 2:
			value19 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

			variant = nginx_lint_plugin_parser_types.MakeConfigItemValueBlankLineItem(nginx_lint_plugin_data_types.BlankLineInfo{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 4))), value19, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))))})

		default:
			panic("unreachable")
		}
		value20 := unsafe.Slice((*uint32)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 24*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 25*4))))

		result21 = append(result21, nginx_lint_plugin_parser_types.ConfigItem{variant, value20})
	}

	value22 := unsafe.Slice((*uint32)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))
	result24 := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4)))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))), index*(2*4))
		value23 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

		result24 = append(result24, value23)
	}

	result25 := ConfigSnapshot{result21, value22, result24}
	return result25

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]config.all-directives-with-context
func wasm_import_method_config_all_directives_with_context(arg0 int32, arg1 uintptr)

func (self *Config) AllDirectivesWithContext() []DirectiveContext {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_config_all_directives_with_context((self).Handle(), returnArea)
	result0 := make([]DirectiveContext, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(4*4))
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value)
		}

		result0 = append(result0, DirectiveContext{DirectiveFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(base), 0))))), result, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))})
	}

	result1 := result0
	return result1

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]config.all-directives
func wasm_import_method_config_all_directives(arg0 int32, arg1 uintptr)

func (self *Config) AllDirectives() []*Directive {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_config_all_directives((self).Handle(), returnArea)
	result := make([]*Directive, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*4)

		result = append(result, DirectiveFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(base), 0))))))
	}

	result0 := result
	return result0

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]config.items
func wasm_import_method_config_items(arg0 int32, arg1 uintptr)

func (self *Config) Items() []ConfigItem {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_config_items((self).Handle(), returnArea)
	result := make([]ConfigItem, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(16+7*4))
		var variant ConfigItem
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
		case 0:

			variant = MakeConfigItemDirectiveItem(DirectiveFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(base), 4))))))

		case 1:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))))
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))))
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 6*4))))

			variant = MakeConfigItemCommentItem(nginx_lint_plugin_data_types.CommentInfo{value, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (3 * 4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 3*4)))), value0, value1, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 7*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 7*4))))})

		case 2:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

			variant = MakeConfigItemBlankLineItem(nginx_lint_plugin_data_types.BlankLineInfo{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 4))), value2, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))))})

		default:
			panic("unreachable")
		}

		result = append(result, variant)
	}

	result3 := result
	return result3

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]config.include-context
func wasm_import_method_config_include_context(arg0 int32, arg1 uintptr)

func (self *Config) IncludeContext() []string {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_config_include_context((self).Handle(), returnArea)
	result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(2*4))
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

		result = append(result, value)
	}

	result0 := result
	return result0

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]config.is-included-from
func wasm_import_method_config_is_included_from(arg0 int32, arg1 uintptr, arg2 uint32) int32

func (self *Config) IsIncludedFrom(context string) bool {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	utf8 := unsafe.Pointer(unsafe.StringData(context))
	pinner.Pin(utf8)
	result := wasm_import_method_config_is_included_from((self).Handle(), uintptr(utf8), uint32(len(context)))
	return (result != 0)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]config.is-included-from-http
func wasm_import_method_config_is_included_from_http(arg0 int32) int32

func (self *Config) IsIncludedFromHttp() bool {

	result := wasm_import_method_config_is_included_from_http((self).Handle())
	return (result != 0)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]config.is-included-from-http-server
func wasm_import_method_config_is_included_from_http_server(arg0 int32) int32

func (self *Config) IsIncludedFromHttpServer() bool {

	result := wasm_import_method_config_is_included_from_http_server((self).Handle())
	return (result != 0)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]config.is-included-from-http-location
func wasm_import_method_config_is_included_from_http_location(arg0 int32) int32

func (self *Config) IsIncludedFromHttpLocation() bool {

	result := wasm_import_method_config_is_included_from_http_location((self).Handle())
	return (result != 0)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]config.is-included-from-stream
func wasm_import_method_config_is_included_from_stream(arg0 int32) int32

func (self *Config) IsIncludedFromStream() bool {

	result := wasm_import_method_config_is_included_from_stream((self).Handle())
	return (result != 0)

}

//go:wasmimport nginx-lint:plugin/config-api@4.0.0 [method]config.immediate-parent-context
func wasm_import_method_config_immediate_parent_context(arg0 int32, arg1 uintptr)

func (self *Config) ImmediateParentContext() witTypes.Option[string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_config_immediate_parent_context((self).Handle(), returnArea)
	var option witTypes.Option[string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[string]()
	case 1:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		option = witTypes.Some[string](value)
	default:
		panic("unreachable")
	}
	result := option
	return result

}
