# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Shared data types used by both the plugin config-api (resource-based)
and the parser output (record-based).
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class ArgumentType(Enum):
    """
    Argument value type
    """
    LITERAL = 0
    QUOTED_STRING = 1
    SINGLE_QUOTED_STRING = 2
    VARIABLE = 3

@dataclass
class ArgumentInfo:
    """
    Argument data (returned as a record since it's small)
    """
    value: str
    raw: str
    arg_type: ArgumentType
    line: int
    column: int
    start_offset: int
    end_offset: int

@dataclass
class CommentInfo:
    """
    Comment data
    """
    text: str
    line: int
    column: int
    leading_whitespace: str
    trailing_whitespace: str
    start_offset: int
    end_offset: int

@dataclass
class BlankLineInfo:
    """
    Blank line data
    """
    line: int
    content: str
    start_offset: int

@dataclass
class DirectiveData:
    """
    All flat properties of a directive (for bulk retrieval)
    """
    name: str
    args: List[ArgumentInfo]
    line: int
    column: int
    start_offset: int
    end_offset: int
    end_line: int
    end_column: int
    leading_whitespace: str
    trailing_whitespace: str
    space_before_terminator: str
    has_block: bool
    block_is_raw: bool
    block_raw_content: Optional[str]
    closing_brace_leading_whitespace: Optional[str]
    block_trailing_whitespace: Optional[str]
    trailing_comment_text: Optional[str]
    name_end_column: int
    name_end_offset: int
    block_start_line: Optional[int]
    block_start_column: Optional[int]
    block_start_offset: Optional[int]


