# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Record-based types for parser output (no resources, no recursion).
Uses index-based references to represent the tree structure:
all config items are stored in a flat array, with child-indices
pointing to children within that array.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import data_types


@dataclass
class ConfigItemValue_DirectiveItem:
    value: data_types.DirectiveData


@dataclass
class ConfigItemValue_CommentItem:
    value: data_types.CommentInfo


@dataclass
class ConfigItemValue_BlankLineItem:
    value: data_types.BlankLineInfo


ConfigItemValue = Union[ConfigItemValue_DirectiveItem, ConfigItemValue_CommentItem, ConfigItemValue_BlankLineItem]
"""
The kind of a config item (non-recursive)
"""


@dataclass
class ConfigItem:
    """
    A config item in the flat all-items array.
    For directive items with blocks, child-indices contains the indices
    of child items within the all-items array.
    """
    value: ConfigItemValue
    child_indices: List[int]

@dataclass
class DirectiveContext:
    """
    A directive paired with its parent block context
    """
    data: data_types.DirectiveData
    block_item_indices: List[int]
    parent_stack: List[str]
    depth: int

@dataclass
class ParseOutput:
    """
    Complete parser output
    """
    directives_with_context: List[DirectiveContext]
    include_context: List[str]
    all_items: List[ConfigItem]
    top_level_indices: List[int]


