// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     nginx-lint:plugin@4.0.0

package nginx_lint_plugin_types

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

const (
	SeverityError   uint8 = 0
	SeverityWarning uint8 = 1
)

type Severity = uint8

type Fix struct {
	Line        uint32
	OldText     witTypes.Option[string]
	NewText     string
	DeleteLine  bool
	InsertAfter bool
	StartOffset witTypes.Option[uint32]
	EndOffset   witTypes.Option[uint32]
}

type LintError struct {
	Rule     string
	Category string
	Message  string
	Severity Severity
	Line     witTypes.Option[uint32]
	Column   witTypes.Option[uint32]
	Fixes    []Fix
}

type PluginSpec struct {
	Name            string
	Category        string
	Description     string
	ApiVersion      string
	Severity        witTypes.Option[string]
	Why             witTypes.Option[string]
	BadExample      witTypes.Option[string]
	GoodExample     witTypes.Option[string]
	References      witTypes.Option[[]string]
	MinNginxVersion witTypes.Option[string]
	MaxNginxVersion witTypes.Option[string]
}
