// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     nginx-lint:plugin@4.0.0

package nginx_lint_plugin_parser_types

import (
	"github.com/walf443/nginx-lint/plugins/go/nginx-lint-plugin/bindings/nginx_lint_plugin_data_types"
)

type CommentInfo = nginx_lint_plugin_data_types.CommentInfo
type BlankLineInfo = nginx_lint_plugin_data_types.BlankLineInfo
type DirectiveData = nginx_lint_plugin_data_types.DirectiveData

const (
	ConfigItemValueDirectiveItem uint8 = 0
	ConfigItemValueCommentItem   uint8 = 1
	ConfigItemValueBlankLineItem uint8 = 2
)

// The kind of a config item (non-recursive)
type ConfigItemValue struct {
	tag   uint8
	value any
}

func (self ConfigItemValue) Tag() uint8 {
	return self.tag
}

func (self ConfigItemValue) DirectiveItem() nginx_lint_plugin_data_types.DirectiveData {
	if self.tag != ConfigItemValueDirectiveItem {
		panic("tag mismatch")
	}
	return self.value.(nginx_lint_plugin_data_types.DirectiveData)
}
func (self ConfigItemValue) CommentItem() nginx_lint_plugin_data_types.CommentInfo {
	if self.tag != ConfigItemValueCommentItem {
		panic("tag mismatch")
	}
	return self.value.(nginx_lint_plugin_data_types.CommentInfo)
}
func (self ConfigItemValue) BlankLineItem() nginx_lint_plugin_data_types.BlankLineInfo {
	if self.tag != ConfigItemValueBlankLineItem {
		panic("tag mismatch")
	}
	return self.value.(nginx_lint_plugin_data_types.BlankLineInfo)
}

func MakeConfigItemValueDirectiveItem(value nginx_lint_plugin_data_types.DirectiveData) ConfigItemValue {
	return ConfigItemValue{ConfigItemValueDirectiveItem, value}
}
func MakeConfigItemValueCommentItem(value nginx_lint_plugin_data_types.CommentInfo) ConfigItemValue {
	return ConfigItemValue{ConfigItemValueCommentItem, value}
}
func MakeConfigItemValueBlankLineItem(value nginx_lint_plugin_data_types.BlankLineInfo) ConfigItemValue {
	return ConfigItemValue{ConfigItemValueBlankLineItem, value}
}

// A config item in the flat all-items array.
// For directive items with blocks, child-indices contains the indices
// of child items within the all-items array.
type ConfigItem struct {
	Value        ConfigItemValue
	ChildIndices []uint32
}

// A directive paired with its parent block context
type DirectiveContext struct {
	Data nginx_lint_plugin_data_types.DirectiveData
	// Indices of block items in the all-items array
	BlockItemIndices []uint32
	ParentStack      []string
	Depth            uint32
}

// Complete parser output
type ParseOutput struct {
	DirectivesWithContext []DirectiveContext
	IncludeContext        []string
	// Flat array of all config items (DFS order)
	AllItems []ConfigItem
	// Indices of top-level items in all-items
	TopLevelIndices []uint32
}
