use std::io::Write;
use std::process::ExitCode;

/// Third-party notices for the crates compiled into this binary, generated by
/// cargo-about from `about.toml` and `about.hbs` (`make build-licenses`).
const NOTICES: &str = include_str!("../../licenses/THIRD-PARTY-NOTICES");

pub fn run_license() -> ExitCode {
    // write_all rather than print!, which panics when the reader (`| head`,
    // a pager) closes the pipe before the text has all been written
    match std::io::stdout().lock().write_all(NOTICES.as_bytes()) {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) if error.kind() == std::io::ErrorKind::BrokenPipe => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("Error: {error}");
            ExitCode::FAILURE
        }
    }
}
