// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     nginx-lint:plugin@4.0.0

package nginx_lint_plugin_data_types

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

const (
	ArgumentTypeLiteral            uint8 = 0
	ArgumentTypeQuotedString       uint8 = 1
	ArgumentTypeSingleQuotedString uint8 = 2
	ArgumentTypeVariable           uint8 = 3
)

// Argument value type
type ArgumentType = uint8

// Argument data (returned as a record since it's small)
type ArgumentInfo struct {
	Value       string
	Raw         string
	ArgType     ArgumentType
	Line        uint32
	Column      uint32
	StartOffset uint32
	EndOffset   uint32
}

// Comment data
type CommentInfo struct {
	Text               string
	Line               uint32
	Column             uint32
	LeadingWhitespace  string
	TrailingWhitespace string
	StartOffset        uint32
	EndOffset          uint32
}

// Blank line data
type BlankLineInfo struct {
	Line        uint32
	Content     string
	StartOffset uint32
}

// All flat properties of a directive (for bulk retrieval)
type DirectiveData struct {
	Name                  string
	Args                  []ArgumentInfo
	Line                  uint32
	Column                uint32
	StartOffset           uint32
	EndOffset             uint32
	EndLine               uint32
	EndColumn             uint32
	LeadingWhitespace     string
	TrailingWhitespace    string
	SpaceBeforeTerminator string
	HasBlock              bool
	BlockIsRaw            bool
	// Actual raw content for raw blocks (e.g., lua code); none if not a raw block
	BlockRawContent witTypes.Option[string]
	// Leading whitespace before the closing brace; none if no block
	ClosingBraceLeadingWhitespace witTypes.Option[string]
	// Trailing whitespace after the closing brace; none if no block
	BlockTrailingWhitespace witTypes.Option[string]
	// Text of the trailing comment on the directive line; none if no comment
	TrailingCommentText witTypes.Option[string]
	// End column of the name token (1-based)
	NameEndColumn uint32
	// End byte offset of the name token (0-based)
	NameEndOffset uint32
	// Start line of the block's opening brace (1-based); none if no block
	BlockStartLine witTypes.Option[uint32]
	// Start column of the block's opening brace (1-based); none if no block
	BlockStartColumn witTypes.Option[uint32]
	// Start byte offset of the block's opening brace (0-based); none if no block
	BlockStartOffset witTypes.Option[uint32]
}
