# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import types
from ..imports import data_types
from ..imports import parser_types

@dataclass
class ConfigSnapshot:
    """
    The entire config as one flat value (see the `snapshot` function)
    """
    all_items: List[parser_types.ConfigItem]
    top_level_indices: List[int]
    include_context: List[str]


@dataclass
class ConfigItem_DirectiveItem:
    value: Any


@dataclass
class ConfigItem_CommentItem:
    value: data_types.CommentInfo


@dataclass
class ConfigItem_BlankLineItem:
    value: data_types.BlankLineInfo


ConfigItem = Union[ConfigItem_DirectiveItem, ConfigItem_CommentItem, ConfigItem_BlankLineItem]
"""
A config item (directive, comment, or blank line)
"""


class Directive:
    """
    An nginx directive (resource backed by host data)
    """
    
    def data(self) -> data_types.DirectiveData:
        """
        Get all flat properties in a single call (optimized for reconstruction)
        """
        raise NotImplementedError
    def name(self) -> str:
        """
        Get the directive name
        """
        raise NotImplementedError
    def is_(self, name: str) -> bool:
        """
        Check if the directive has the given name
        """
        raise NotImplementedError
    def first_arg(self) -> Optional[str]:
        """
        Get the first argument value
        """
        raise NotImplementedError
    def first_arg_is(self, value: str) -> bool:
        """
        Check if the first argument equals the given value
        """
        raise NotImplementedError
    def arg_at(self, index: int) -> Optional[str]:
        """
        Get the argument at the given index
        """
        raise NotImplementedError
    def last_arg(self) -> Optional[str]:
        """
        Get the last argument value
        """
        raise NotImplementedError
    def has_arg(self, value: str) -> bool:
        """
        Check if any argument equals the given value
        """
        raise NotImplementedError
    def arg_count(self) -> int:
        """
        Return the number of arguments
        """
        raise NotImplementedError
    def args(self) -> List[data_types.ArgumentInfo]:
        """
        Get all arguments as records
        """
        raise NotImplementedError
    def line(self) -> int:
        """
        Get the start line number (1-based)
        """
        raise NotImplementedError
    def column(self) -> int:
        """
        Get the start column number (1-based)
        """
        raise NotImplementedError
    def start_offset(self) -> int:
        """
        Get the start byte offset (0-based)
        """
        raise NotImplementedError
    def end_offset(self) -> int:
        """
        Get the end byte offset (0-based)
        """
        raise NotImplementedError
    def leading_whitespace(self) -> str:
        """
        Get the leading whitespace before the directive
        """
        raise NotImplementedError
    def trailing_whitespace(self) -> str:
        """
        Get the trailing whitespace after the directive
        """
        raise NotImplementedError
    def space_before_terminator(self) -> str:
        """
        Get the space before the terminator (; or {)
        """
        raise NotImplementedError
    def has_block(self) -> bool:
        """
        Check if the directive has a block
        """
        raise NotImplementedError
    def block_items(self) -> List[ConfigItem]:
        """
        Get the items inside the directive's block
        """
        raise NotImplementedError
    def block_is_raw(self) -> bool:
        """
        Check if the block contains raw content (e.g., lua blocks)
        """
        raise NotImplementedError
    def replace_with(self, new_text: str) -> types.Fix:
        """
        Create a fix that replaces this directive with new text
        """
        raise NotImplementedError
    def delete_line_fix(self) -> types.Fix:
        """
        Create a fix that deletes this directive's line
        """
        raise NotImplementedError
    def insert_after(self, new_text: str) -> types.Fix:
        """
        Create a fix that inserts a new line after this directive
        """
        raise NotImplementedError
    def insert_before(self, new_text: str) -> types.Fix:
        """
        Create a fix that inserts a new line before this directive
        """
        raise NotImplementedError
    def insert_after_many(self, lines: List[str]) -> types.Fix:
        """
        Create a fix that inserts multiple lines after this directive
        """
        raise NotImplementedError
    def insert_before_many(self, lines: List[str]) -> types.Fix:
        """
        Create a fix that inserts multiple lines before this directive
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class DirectiveContext:
    """
    A directive paired with its parent block context
    """
    directive: Directive
    parent_stack: List[str]
    depth: int

class Config:
    """
    The parsed nginx configuration (resource backed by host data)
    """
    
    def snapshot(self) -> ConfigSnapshot:
        """
        Get the entire config as one flat snapshot in a single call.
        Bulk alternative to walking items/data/block-items per directive:
        one host call transfers everything, which avoids per-directive
        call overhead when reconstructing the whole tree guest-side.
        """
        raise NotImplementedError
    def snapshot_filtered(self, names: List[str]) -> ConfigSnapshot:
        """
        Get a snapshot pruned to directives whose name is in `names`,
        plus the ancestor directives needed to preserve block-context
        queries (e.g. `is-inside("http")`) for the matches. Directives
        outside every match's ancestor chain are dropped entirely, so
        the transferred/reconstructed tree is proportional to how much
        of the config is actually relevant, not its total size.
        Comments and blank lines are always omitted from this snapshot.
        """
        raise NotImplementedError
    def all_directives_with_context(self) -> List[DirectiveContext]:
        """
        Iterate over all directives recursively with parent context
        """
        raise NotImplementedError
    def all_directives(self) -> List[Directive]:
        """
        Iterate over all directives recursively
        """
        raise NotImplementedError
    def items(self) -> List[ConfigItem]:
        """
        Get the top-level config items
        """
        raise NotImplementedError
    def include_context(self) -> List[str]:
        """
        Get the include context (parent block names from include directive)
        """
        raise NotImplementedError
    def is_included_from(self, context: str) -> bool:
        """
        Check if this config is included from within a specific context
        """
        raise NotImplementedError
    def is_included_from_http(self) -> bool:
        """
        Check if included from http context
        """
        raise NotImplementedError
    def is_included_from_http_server(self) -> bool:
        """
        Check if included from http > server context
        """
        raise NotImplementedError
    def is_included_from_http_location(self) -> bool:
        """
        Check if included from http > ... > location context
        """
        raise NotImplementedError
    def is_included_from_stream(self) -> bool:
        """
        Check if included from stream context
        """
        raise NotImplementedError
    def immediate_parent_context(self) -> Optional[str]:
        """
        Get the immediate parent context
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



