# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class Severity(Enum):
    ERROR = 0
    WARNING = 1

@dataclass
class Fix:
    line: int
    old_text: Optional[str]
    new_text: str
    delete_line: bool
    insert_after: bool
    start_offset: Optional[int]
    end_offset: Optional[int]

@dataclass
class LintError:
    rule: str
    category: str
    message: str
    severity: Severity
    line: Optional[int]
    column: Optional[int]
    fixes: List[Fix]

@dataclass
class PluginSpec:
    name: str
    category: str
    description: str
    api_version: str
    severity: Optional[str]
    why: Optional[str]
    bad_example: Optional[str]
    good_example: Optional[str]
    references: Optional[List[str]]
    min_nginx_version: Optional[str]
    max_nginx_version: Optional[str]


