// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     nginx-lint:plugin@4.0.0

package wit_world

import (
	"github.com/walf443/nginx-lint/plugins/go/nginx-lint-plugin/bindings/nginx_lint_plugin_config_api"
	"github.com/walf443/nginx-lint/plugins/go/nginx-lint-plugin/bindings/nginx_lint_plugin_types"
)

type PluginSpec = nginx_lint_plugin_types.PluginSpec
type LintError = nginx_lint_plugin_types.LintError
type Config = nginx_lint_plugin_config_api.Config
