# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from .imports import types
from .imports import config_api


class WitWorld(Protocol):

    @abstractmethod
    def spec(self) -> types.PluginSpec:
        """
        Return plugin metadata
        """
        raise NotImplementedError

    @abstractmethod
    def check(self, cfg: config_api.Config, path: str) -> List[types.LintError]:
        """
        Check config and return lint errors
        """
        raise NotImplementedError

